platform :ios, '12.0'
use_frameworks!
target ‘DistractionFreeYoutube’ do
    pod 'GoogleAPIClientForREST/YouTube', '~> 1.2.1'
    pod 'Google/SignIn', '~> 3.0.3'
    pod "youtube-ios-player-helper", "~> 1.0.4"
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
